---
title: "Tugas Komstat"
author: "Ridson Alfarizal"
date: "10/11/2020"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Buku Walpole Hal 258

No 11
```{r}
kaleng_sabun <- c(10.2, 9.7, 10.1, 10.3, 10.1, 9.8, 9.9, 10.4, 10.3, 9.8)
#Uji Normalitas
shapiro.test(kaleng_sabun)

t.test(kaleng_sabun, conf.level = 0.99)
```

No 20
```{r}
perusahaan1 = c(103, 94, 110, 87, 98)
perusahaan2 = c(97, 82, 123, 92, 175, 88, 118)

#Uji normalitas
shapiro.test(perusahaan1)
shapiro.test(perusahaan2)

var.test(perusahaan1, perusahaan2, conf.level = 0.92)


t.test(perusahaan1, perusahaan2, var.equal = F, conf.level = 0.90, alternative = "two.sided")

```

No 21
```{r}
varietas1 = c(38, 23, 35, 41, 44, 29, 37, 31, 38)
varietas2 = c(45, 25, 31, 38, 50, 33, 36, 40, 43)

#uji Normalitas
shapiro.test(varietas2-varietas1)

t.test(varietas2, varietas1, paired = T, conf.level = 0.95, alternative = "two.sided")
```

No 22
```{r}
merk_a = c(34400, 45500, 36700, 32000, 48400, 32800, 38100, 30100)
merk_b = c(36700, 46800, 37700, 31100, 47800, 36400, 38900, 31500)

#Uji normalitas
shapiro.test(merk_a-merk_b)

t.test(merk_a, merk_b, paired = T, conf.level = 0.99, alternative = "two.sided")
```

No 23
```{r}
bobot_sebelum = c(58.5, 60.3, 61.7, 69, 64, 62.6, 56.7)
bobot_sesudah = c(60, 54.9, 58.1, 62.1, 58.5, 59.9, 54.5)

#Uji Normalitas
shapiro.test(bobot_sesudah-bobot_sebelum)

t.test(bobot_sesudah, bobot_sebelum, paired = T, conf.level = 0.95, alternative = "less", mu=4.5)
```

## Buku Hal 308
Teladan 7
```{r}
anggota = c(2, 2, 2.3, 2.1, 2.4)
bukan_anggota = c(2.2, 1.9, 2.5, 2.3, 2.4)

#Uji normalitas
shapiro.test(anggota-bukan_anggota)

t.test(anggota, bukan_anggota, paired = T, conf.level = 0.95, alternative = "less")
```


## Buku Hal 311 
No 17 
```{r}
perusahaan1 = c(102, 86, 98, 109, 92)
perusahaan2 = c(81, 165, 97, 134, 92, 87, 114)

#Uji normalitas
shapiro.test(perusahaan1)
shapiro.test(perusahaan2)

#Uji Homogenitas Varians
var.test(perusahaan2, perusahaan1)

t.test(perusahaan1, perusahaan2, var.equal = F, alternative = "greater", mu=10, conf.level = 0.9)
```
